#!/bin/sh

# Give Xorg setgid to /dev/input.
chown :input "$BLOS_ROOT/usr/bin/Xorg"
chmod g+s    "$BLOS_ROOT/usr/bin/Xorg"

cat <<EOF

NOTE: You must be a part of the [1mvideo[m group
      for rootless xorg-server to work.

NOTE: This groups based permissions model may not
      be suitable if blOS will be used as a multi
      user system. Further configuration can be
      done at your own discretion.

-> addgroup USER video

EOF
